[package]
name = "musicus_rs"
version = "0.1.0"
authors = ["Bluemi <bruno.schilling@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.13.0"

[dependencies.pancurses]
version = "0.16.1"
features = ["wide"]
